"""second migration

Revision ID: 0f32b2531c84
Revises: 12a5e8703d6c
Create Date: 2022-11-04 23:40:05.506354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f32b2531c84'
down_revision = '12a5e8703d6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
