"""migration

Revision ID: 12a5e8703d6c
Revises: 87d3f57b3df0
Create Date: 2022-11-04 23:39:28.720304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a5e8703d6c'
down_revision = '87d3f57b3df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
