"""Modified description column

Revision ID: 324822f22037
Revises: eacf6684207c
Create Date: 2022-10-27 16:26:34.744043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324822f22037'
down_revision = 'eacf6684207c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'secret_key',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=260),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'secret_key',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
