"""Added user id

Revision ID: 552976db2289
Revises: 1e8922caec0b
Create Date: 2022-09-27 15:24:02.424306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552976db2289'
down_revision = '1e8922caec0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    op.add_column('cards', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'users', ['user_id'], ['id'])
    op.add_column('vaults', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vaults', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaults', type_='foreignkey')
    op.drop_column('vaults', 'user_id')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'user_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
