"""migration

Revision ID: 87d3f57b3df0
Revises: 7c7eaa11a94a
Create Date: 2022-11-04 23:39:15.266118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d3f57b3df0'
down_revision = '7c7eaa11a94a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
