"""Update password size

Revision ID: 885b35467e4e
Revises: 324822f22037
Create Date: 2022-10-28 16:01:42.875515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885b35467e4e'
down_revision = '324822f22037'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'password',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=260),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'password',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
