"""Delete unique

Revision ID: 9bca79c8cbf8
Revises: 552976db2289
Create Date: 2022-09-27 15:31:50.822573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bca79c8cbf8'
down_revision = '552976db2289'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cards_ccv_key', 'cards', type_='unique')
    op.drop_index('ix_cards_name', table_name='cards')
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.drop_index('ix_cards_number', table_name='cards')
    op.create_index(op.f('ix_cards_number'), 'cards', ['number'], unique=False)
    op.drop_index('ix_vaults_name', table_name='vaults')
    op.create_index(op.f('ix_vaults_name'), 'vaults', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaults_name'), table_name='vaults')
    op.create_index('ix_vaults_name', 'vaults', ['name'], unique=False)
    op.drop_index(op.f('ix_cards_number'), table_name='cards')
    op.create_index('ix_cards_number', 'cards', ['number'], unique=False)
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.create_index('ix_cards_name', 'cards', ['name'], unique=False)
    op.create_unique_constraint('cards_ccv_key', 'cards', ['ccv'])
    # ### end Alembic commands ###
