"""Add User, Vault, Account, Card models

Revision ID: b6bc57c2026f
Revises: b1539023dc15
Create Date: 2022-09-23 00:26:53.179235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bc57c2026f'
down_revision = 'b1539023dc15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
